### ISSUE TITLE
Fatal Error on saving products.

### ISSUE THREAD

**Issue by addedlovely** [facebookincubator/facebook-for-woocommerce#49]
Upon saving some products a 500 server error is thrown. From the logs:

```
[22-Sep-2017 06:18:09 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /home/case/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:1145
Stack trace:
#0 /public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(660): WC_Facebookcommerce_Integration->check_api_result(Object(WP_Error))
#1 /public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(464): WC_Facebookcommerce_Integration->update_product_group(Object(WC_Product_Variable))
#2 /public_html/wp-includes/class-wp-hook.php(298): WC_Facebookcommerce_Integration->on_variable_product_publish(448)
#3 /public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#4 /public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(368): do_action('woocommerce_pro...', 448)
#6 /public_html/wp-includes/c in /home/case/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 1145

```

WooCommerce version 3.1.2 
WordPress version 4.8.2

**Comment by dmitridr** [comment]
Hello,

Thanks for the stack trace, from the line #s it seems to be from an older version.
Could you confirm that you are running version 1.6.0 or higher, and upgrade if not? It may fix the issue. WP_Error should have been handled in 1.4.x and higher.

**Comment by addedlovely** [comment]
@dmitridr Ah apologies, have updated and the issue is resolved. Oddly we weren't get any update notifications about the plugin in WordPress.
