### ISSUE TITLE
Facebook extension error: Facebook for WooCommerce Unsupported post request.

### ISSUE THREAD

**Issue by FifthCreations** [facebookincubator/facebook-for-woocommerce#908]
Also getting this new message when trying to add new products or update old ones.  Happened with the last woocommerce update.  Here is my error log.  I've done the steps I have seen in other posts with no luck.  I've got checkmarks in all my settings.  Again, happened with last update to woocommerce, which I did yesterday and then there was a new update today but still did not fix it.  Any new advice would be wonderful.

2019-03-08T03:05:24+00:00 CRITICAL Uncaught Error: Call to undefined method WC_Facebookcommerce_Integration::sync_all_products() in /home/internetbiz15/public_html/fifth.energy/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:1862
Stack trace:
#0 /home/internetbiz15/public_html/fifth.energy/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(1795): WC_Facebookcommerce_Integration->sync_all_fb_products_using_feed()
#1 /home/internetbiz15/public_html/fifth.energy/wp-includes/class-wp-hook.php(286): WC_Facebookcommerce_Integration->ajax_sync_all_fb_products_using_feed('')
#2 /home/internetbiz15/public_html/fifth.energy/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /home/internetbiz15/public_html/fifth.energy/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#4 /home/internetbiz15/public_html/fifth.energy/wp-admin/admin-ajax.php(167): do_action('wp_ajax_ajax_sy...')
#5 {main}
  thrown in /home/internetbiz15/public_html/fifth.energy/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 1862

**Comment by FifthCreations** [comment]
It's working today, thank you to whoever fixed it!
